name = "StrojniSoucasti"
uuid = "10255254-1473-4e7e-b938-74a6d2bcadf3"
version = "0.1.11"
authors = ["Martin"]

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.12"

Printf = "1"
TOML = "1"
Unitful = "1.27"
