name = "StrojniSoucasti"
uuid = "10255254-1473-4e7e-b938-74a6d2bcadf3"
version = "0.1.5"
authors = ["Martin"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
OdsIO = "56b0d19f-0a74-5872-92bc-f48f9c5431d4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpravaSouboru = "bacb9340-e1dc-42c9-a0b3-58db5d1f30f5"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
Dates = "1.11.0"
FileIO = "1.17.1"
FilePathsBase = "0.9.24"
JLD2 = "0.6.3"
OdsIO = "0.6.3"
Plots = "1.41.1"
Printf = "1.11.0"
Revise = "3.13.0"
Tables = "1.12.1"
Test = "1.11.0"
Unitful = "1.27.0"
XLSX = "0.10.4"
