
schema_version = "1.0.0"

["40"]
name = "40x40"
standard = "ČSN 42 5720"
a = 40
b = 40
t = [3.0, 3.5, 4.0, 4.5, 5.0]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]

["50x35"]
name = "50x35"
standard = "ČSN 42 5720"
a = 50
b = 35
t = [3.0, 3.5, 4.0, 4.5, 5.0]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]
