
schema_version = "1.0.0"

["10"]
name = "10x10"
standard = "ČSN 42 5720"
a = 10
b = 10
t = [1]
material = ["11 353", "11 453", "11 523"]

["15x10"]
name = "15x10"
standard = "ČSN 42 5720"
a = 15
b = 10
t = [1.5]
material = ["11 353", "11 453", "11 523"]

["20"]
name = "20x20"
standard = "ČSN 42 5720"
a = 20
b = 20
t = [2]
material = ["11 353", "11 453", "11 523"]

["25"]
name = "25x25"
standard = "ČSN 42 5720"
a = 25
b = 25
t = [3]
material = ["11 353", "11 453", "11 523"]

["30x20"]
name = "30x20"
standard = "ČSN 42 5720"
a = 30
b = 20
t = [3]
material = ["11 353", "11 453", "11 523"]

["40"]
name = "40x40"
standard = "ČSN 42 5720"
a = 40
b = 40
t = [3.0, 3.5, 4.0, 4.5, 5.0]
material = ["11 353", "11 453", "11 523"]

["50x35"]
name = "50x35"
standard = "ČSN 42 5720"
a = 50
b = 35
t = [3, 3.5, 4, 4.5, 5]
material = ["11 353", "11 453", "11 523"]

["60"]
name = "60x60"
standard = "ČSN 42 5720"
a = 60
b = 60
t = [4, 5, 6.3]
material = ["11 353", "11 453", "11 523"]

["60x40"]
name = "60x40"
standard = "ČSN 42 5720"
a = 60
b = 40
t = [6]
material = ["11 353", "11 453", "11 523"]

["80"]
name = "80x80"
standard = "ČSN 42 5720"
a = 80
b = 80
t = [5, 6.3, 8]
material = ["11 353", "11 453", "11 523"]

["80x40"]
name = "80x40"
standard = "ČSN 42 5720"
a = 80
b = 40
t = [4, 5, 6.3]
material = ["11 353", "11 453", "11 523"]

["100"]
name = "100x100"
standard = "ČSN 42 5720"
a = 100
b = 100
t = [6.3, 8, 10]
material = ["11 353", "11 453", "11 523"]

["100x50"]
name = "100x50"
standard = "ČSN 42 5720"
a = 100
b = 50
t = [5, 6.3, 8]
material = ["11 353", "11 453", "11 523"]

["120"]
name = "120x120"
standard = "ČSN 42 5720"
a = 120
b = 120
t = [8, 10, 12,5]
material = ["11 353", "11 453", "11 523"]

["120x60"]
name = "120x60"
standard = "ČSN 42 5720"
a = 120
b = 60
t = [6.3, 8, 10]
material = ["11 353", "11 453", "11 523"]

["130"]
standart = "ČSN 42 5720"
t = [8, 10, 12, 16]
material = ["11 353", "11 453", "11 523"]

["150"]
name = "150x150"
standard = "ČSN 42 5720"
a = 150
b = 150
t = [10, 12.5, 16]
material = ["11 353", "11 453", "11 523"]

["160x80"]
name = "160x80"
standard = "ČSN 42 5720"
a = 160
b = 80
t = [8, 10, 12.5]
material = ["11 353", "11 453", "11 523"]
