
schema_version = "1.0.0"

["10"]
standard = "ČSN 42 5720"
t = [1]
material = ["11 353", "11 453", "11 523"]

["15x10"]
standard = "ČSN 42 5720"
t = [1.5]
material = ["11 353", "11 453", "11 523"]

["20"]
standard = "ČSN 42 5720"
t = [2]
material = ["11 353", "11 453", "11 523"]

["25"]
standard = "ČSN 42 5720"
t = [3]
material = ["11 353", "11 453", "11 523"]

["30x20"]
standard = "ČSN 42 5720"
t = [3]
material = ["11 353", "11 453", "11 523"]

["40"]
standard = "ČSN 42 5720"
t = [3.0, 3.5, 4.0, 4.5, 5.0]
material = ["11 353", "11 453", "11 523"]

["50x35"]
standard = "ČSN 42 5720"
t = [3, 3.5, 4, 4.5, 5]
material = ["11 353", "11 453", "11 523"]

["60"]
standard = "ČSN 42 5720"
t = [4, 5, 6.3]
material = ["11 353", "11 453", "11 523"]

["60x40"]
standard = "ČSN 42 5720"
t = [6]
material = ["11 353", "11 453", "11 523"]

["80"]
standard = "ČSN 42 5720"
t = [5, 6.3, 8]
material = ["11 353", "11 453", "11 523"]

["80x40"]
standard = "ČSN 42 5720"
t = [4, 5, 6.3]
material = ["11 353", "11 453", "11 523"]

["100"]
standard = "ČSN 42 5720"
t = [5, 6]
material = ["11 353", "11 453", "11 523"]

["100x50"]
standard = "ČSN 42 5720"
t = [5, 6.3, 8]
material = ["11 353", "11 453", "11 523"]

["120"]
standard = "ČSN 42 5720"
t = [8, 10, 12,5]
material = ["11 353", "11 453", "11 523"]

["120x60"]
standard = "ČSN 42 5720"
t = [6.3, 8, 10]
material = ["11 353", "11 453", "11 523"]

["125"]
standart = "ČSN 42 5720"
t = [6]
material = ["11 353", "11 453", "11 523"]

["130"]
standart = "ČSN 42 5720"
t = [8, 10, 12, 16]
material = ["11 353", "11 453", "11 523"]

["150"]
standard = "ČSN 42 5720"
t = [8, 10, 12, 16]
material = ["11 353", "11 453", "11 523"]

["160x80"]
standard = "ČSN 42 5720"
t = [8, 10, 12.5]
material = ["11 353", "11 453", "11 523"]
