
schema_version = "1.0.0"

["10"]
name = "10x10"
standard = "ČSN 42 5720"
a = 10
b = 10
t = [1.0]
R = [8.0]
material = ["11 353", "11 453", "11 523"]

["15x10"]
name = "15x10"
standard = "ČSN 42 5720"
a = 15
b = 10
t = [1.5]
R = [8.0]
material = ["11 353", "11 453", "11 523"]

["20"]
name = "20x20"
standard = "ČSN 42 5720"
a = 20
b = 20
t = [2.0]
R = [8.0]
material = ["11 353", "11 453", "11 523"]

["25"]
name = "25x25"
standard = "ČSN 42 5720"
a = 25
b = 25
t = [3.0]
R = [8.0]
material = ["11 353", "11 453", "11 523"]

["30x20"]
name = "30x20"
standard = "ČSN 42 5720"
a = 30
b = 20
t = [3.0]
R = [8.0]
material = ["11 353", "11 453", "11 523"]

["40"]
name = "40x40"
standard = "ČSN 42 5720"
a = 40
b = 40
t = [3.0, 3.5, 4.0, 4.5, 5.0]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]

["50x35"]
name = "50x35"
standard = "ČSN 42 5720"
a = 50
b = 35
t = [3.0, 3.5, 4.0, 4.5, 5.0]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]

["60"]
name = "60x60"
standard = "ČSN 42 5720"
a = 60
b = 60
t = [4.0, 5.0, 6.3]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]

["80"]
name = "40x40"
standard = "ČSN 42 5720"
a = 40
b = 40
t = [5.0, 6.3, 8]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]

["80x40"]
name = "40x40"
standard = "ČSN 42 5720"
a = 40
b = 40
t = [4, 5, 6.3]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]

["100"]
name = "40x40"
standard = "ČSN 42 5720"
a = 40
b = 40
t = [6.3, 8, 10]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]

["100x50"]
name = "40x40"
standard = "ČSN 42 5720"
a = 40
b = 40
t = [5, 6.3, 8]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]

["120"]
name = "40x40"
standard = "ČSN 42 5720"
a = 40
b = 40
t = [8, 10, 12,5]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]

["120x60"]
name = "40x40"
standard = "ČSN 42 5720"
a = 40
b = 40
t = [6.3, 8, 10]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]

["150"]
name = "40x40"
standard = "ČSN 42 5720"
a = 40
b = 40
t = [10, 12.5, 16]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]

["160x80"]
name = "40x40"
standard = "ČSN 42 5720"
a = 40
b = 40
t = [8, 10, 12.5]
R = [8.0, 8.0, 8.0, 8.0, 8.0]
material = ["11 353", "11 453", "11 523"]
