
schema_version = "1.0.0"

["S235"]
name = "S235"
standard = "EN 10025-2"
druh = "konstrukční ocel"
Re = 235
Rm_min = 360
Rm_max = 510
A = 26
KV = 27
T_KV = 20
weldable = true
thickness_max = 200
E = 210
G = 81
ny = 0.3
rho = 7850

["S235JR+N"]
name = "S235JR+N"
standard = "EN 10025-2"
druh = "konstrukční ocel"
Re = 235
Rm_min = 360
Rm_max = 510
A = 26
KV = 27
T_KV = 20
weldable = true
thickness_max = 200
E = 210
G = 81
ny = 0.3
rho = 7850

["S235J2+N"]
name = "S235J2+N"
standard = "EN 10025-2"
druh = "konstrukční ocel"
Re = 235
Rm_min = 360
Rm_max = 510
A = 26
KV = 27
T_KV = -20
weldable = true
thickness_max = 200
E = 210
G = 81
ny = 0.3
rho = 7850

["S355JR+N"]
name = "S355JR+N"
standard = "EN 10025-2"
druh = "konstrukční ocel"
Re = 355
Rm_min = 470
Rm_max = 630
A = 22
KV = 27
T_KV = 20
weldable = true
thickness_max = 200
E = 210
G = 81
ny = 0.3
rho = 7850

["S355J2+N"]
name = "S355J2+N"
standard = "EN 10025-2"
druh = "konstrukční ocel"
Re = 355
Rm_min = 470
Rm_max = 630
A = 22
KV = 27
T_KV = -20
weldable = true
thickness_max = 200
E = 210
G = 81
ny = 0.3
rho = 7850
