
schema_version = "1.0.0"

["11373"]
name = "11 373"
standard = "ČSN"
Re = 250
Rm_min = 370
Rm_max = 370
A = 7
KV = 27
T_KV = 20
weldable = true
thickness_max = 200
E = 210
G = 81
ny = 0.3
rho = 7850

["11373žíhaný"]
name = "11 373 žíhaný"
standard = "ČSN"
Re = 220
Rm_min = 350
Rm_max = 370
A = 20
KV = 27
T_KV = 20
weldable = true
thickness_max = 200
E = 210
G = 81
ny = 0.3
rho = 7850

["16440"]
name = "16 440"
standard = "ČSN"
Re = 400
Rm_min = 650
Rm_max = 750
A = 12
KV = 35
T_KV = 20
weldable = true
thickness_max = 200
E = 210
G = 81
ny = 0.3
rho = 7850

["16440zušlechtěno"]
name = "16 440 zušlechtěno"
standard = "ČSN"
Re = 700
Rm_min = 900
Rm_max = 1100
A = 12
KV = 35
T_KV = 20
weldable = true
thickness_max = 200
E = 210
G = 81
ny = 0.3
rho = 7850
