
schema_version = "1.0.0"

["S235"]
name = "S235"
standard = "EN 10025-2"
Re = 235.0
Rm_min = 360.0
Rm_max = 510.0
A = 26.0
KV = 27.0
T_KV = 20.0
weldable = true
thickness_max = 200.0
E = 210
G = 81
ny = 0.3
rho = 7850

["S235JR+N"]
name = "S235JR+N"
standard = "EN 10025-2"
Re = 235.0
Rm_min = 360.0
Rm_max = 510.0
A = 26.0
KV = 27.0
T_KV = 20.0
weldable = true
thickness_max = 200.0
E = 210
G = 81
ny = 0.3
rho = 7850

["S235J2+N"]
name = "S235J2+N"
standard = "EN 10025-2"
Re = 235.0
Rm_min = 360.0
Rm_max = 510.0
A = 26.0
KV = 27.0
T_KV = -20.0
weldable = true
thickness_max = 200.0
E = 210
G = 81
ny = 0.3
rho = 7850

["S355JR+N"]
name = "S355JR+N"
standard = "EN 10025-2"
Re = 355.0
Rm_min = 470.0
Rm_max = 630.0
A = 22.0
KV = 27.0
T_KV = 20.0
weldable = true
thickness_max = 200.0
E = 210
G = 81
ny = 0.3
rho = 7850

["S355J2+N"]
name = "S355J2+N"
standard = "EN 10025-2"
Re = 355.0
Rm_min = 470.0
Rm_max = 630.0
A = 22.0
KV = 27.0
T_KV = -20.0
weldable = true
thickness_max = 200.0
E = 210
G = 81
ny = 0.3
rho = 7850

["11373"]
name = "11373"
standard = "ČSN"
Re = 250.0
Rm_min = 370.0
Rm_max = 370.0
A = 7.0
KV = 27.0
T_KV = 20.0
weldable = true
thickness_max = 200.0
E = 210.0
G = 81.0
ny = 0.3
rho = 7850.0

["11373 žíhaný"]
name = "11373 žíhaný"
standard = "ČSN"
Re = 220.0
Rm_min = 350.0
Rm_max = 370.0
A = 20.0
KV = 27.0
T_KV = 20.0
weldable = true
thickness_max = 200.0
E = 210.0
G = 81.0
ny = 0.3
rho = 7850.0

["16440"]
name = "16440"
standard = "ČSN"
Re = 400.0
Rm_min = 650.0
Rm_max = 750.0
A = 12.0
KV = 35.0
T_KV = 20.0
weldable = true
thickness_max = 200.0
E = 210.0
G = 81.0
ny = 0.3
rho = 7850.0

["16440 zušlechtěno"]
name = "16440 zušlechtěno"
standard = "ČSN"
Re = 700.0
Rm_min = 900.0
Rm_max = 1100.0
A = 12.0
KV = 35.0
T_KV = 20.0
weldable = true
thickness_max = 200.0
E = 210.0
G = 81.0
ny = 0.3
rho = 7850.0
