
schema_version = "1.0.0"

["M1"]
d = 1
p_norm = 0.25
p = 0.25

["M1.2"]
d = 1.2
p_norm = 0.25
p = 0.25

["M1.4"]
d = 1.4
p_norm = 0.3
p = 0.3

["M1.6"]
d = 1.6
p_norm = 0.35
p = 0.35

["M1.8"]
d = 1.8
p_norm = 0.35
p = 0.35

["M2"]
d = 2
p_norm = 0.4
p = 0.4

["M2.5"]
d = 2.5
p_norm = 0.45
p = 0.45

["M3"]
d = 3
p_norm = 0.5
p = 0.5

["M4"]
d = 4
p_norm = 0.7
p = 0.7

["M5"]
d = 5
p_norm = 0.8
p = 0.8

["M6"]
d = 6
p_norm = 1
p = 1

["M6x0.5"]
d = 6
p = 0.5

["M8"]
d = 8
p_norm = 1.25
p = 1.25

["M8x1"]
d = 8
p = 1

["M10"]
d = 10
p_norm = 1.5
p = 1.5

["M10x1.25"]
d = 10
p = 1.25

["M12"]
d = 12
p_norm = 1.75
p = 1.75

["M14"]
d = 14
p_norm = 2
p = 2

["M16"]
d = 16
p_norm = 2
p = 2

["M18"]
d = 18
p_norm = 2.5
p = 2.5

["M20"]
d = 20
p_norm = 2.5
p = 2.5

["M22"]
d = 22
p_norm = 2.5
p = 2.5

["M24"]
d = 24
p_norm = 3
p = 3

["M27"]
d = 27
p_norm = 3
p = 3

["M30"]
d = 30
p_norm = 3.5
p = 3.5

["M33"]
d = 33
p_norm = 3.5
p = 3.5

["M36"]
d = 36
p_norm = 4
p = 4
