
schema_version = "1.0.0"

["M6"]
d = 6.0
pitch = 1.0

["M6x0.5"]
d = 6.0
pitch = 0.5

["M8"]
d = 8.0
pitch = 1.25

["M8x1"]
d = 8.0
pitch = 1

["M10"]
d = 10.0
pitch = 1.5

["M10x1.25"]
d = 10.0
pitch = 1.25
