
schema_version = "1.0.0"

["M1"]
d = 1.0
p = 0.25

["M1.2"]
d = 1.2
p = 0.25

["M1.4"]
d = 1.4
p = 0.3

["M1.6"]
d = 1.6
p = 0.35

["M1.8"]
d = 1.8
p = 0.35

["M2"]
d = 2.0
p = 0.4

["M2.5"]
d = 2.5
p = 0.45

["M3"]
d = 3.0
p = 0.5

["M4"]
d = 4.0
p = 0.7

["M5"]
d = 5.0
p = 0.8

["M6"]
d = 6.0
p = 1.0

["M6x0.5"]
d = 6.0
p = 0.5

["M8"]
d = 8.0
p = 1.25

["M8x1"]
d = 8.0
p = 1

["M10"]
d = 10.0
p = 1.5

["M10x1.25"]
d = 10.0
p = 1.25

["M12"]
d = 12.0
p = 1.75

["M14"]
d = 14.0
p = 2.0

["M16"]
d = 16.0
p = 2.0

["M18"]
d = 18.0
p = 2.5

["M20"]
d = 20.0
p = 2.5

["M22"]
d = 22.0
p = 2.5

["M24"]
d = 24.0
p = 3.0

["M27"]
d = 27.0
p = 3.0

["M30"]
d = 30.0
p = 3.5

["M33"]
d = 33.0
p = 3.5

["M36"]
d = 36.0
p = 4.0